// This configuration enable SimpleORM to use FireDAC Components to Query
{$DEFINE SIMPLEORM_FIREDAC}

// This configuration enable SimpleORM to use RestDW Components to Query
{$DEFINE SIMPLEORM_RESTDW}

// This configuration enable SimpleORM to use UniDAC Components to Query
{$DEFINE SIMPLEORM_UNIDAC}

// This configuration enable SimpleORM to use Zeos Components to Query
{$DEFINE SIMPLEORM_ZEOS}